
STATE_NOT_CONNECTED = 0
STATE_CONNECTED = 1
STATE_INITIALISING = 2
STATE_READY_FOR_SETUP = 3
STATE_PLAYER_INTRODUCED = 4
STATE_PLAYER_CHECK_SETTINGS = 5
STATE_PLAYER_PREPARE_GAME = 6
STATE_PLAYING = 7
STATE_GAME_OVER = 8
